### ISSUE TITLE
frx and fry tags wrong scaling

### ISSUE THREAD

**Issue by vxzms** [pinterf/xy-VSFilter#17]
I open an issue in https://github.com/HomeOfVapourSynthEvolution/xy-VSFilter/issues/1

I test it in Avisynth get same wrong effect.

Avisynth test script:
```C
BlankClip(length=120, width=1920, height=1080, fps=24000, fps_denominator=1001, pixel_type="YV12")
TextSub(file="test.ass")
```

**Comment by pinterf** [comment]
So the fix is Masaiki/VSFilterMod@49c31e5.
Unfortunately the two codebase is significantly different.
xy-VsFilter already handles scalex and scaley but in a some minutes' effort I don't get it why it doesn't work so it needs a longer examination.
