### ISSUE TITLE
WebVTT support

### ISSUE THREAD

**Issue by bagusnl** [pinterf/xy-VSFilter#18]
Knowing that WebVTT is getting more popular as YouTube is using it, can WebVTT support be added to xy-VSFilter?

Here's the Pin Info dump from xySubFilter
```
Filter : XySubFilter - CLSID : {2DFCB782-EC20-4A7C-B530-4577ADB33F21}

- Connected to:

CLSID: {B98D13E7-55DB-4385-A33D-09FD1BA26338}
Filter: LAV Splitter Source
Pin: Subtitle

- Connection media type:

Subtitle

AM_MEDIA_TYPE: 
majortype: Unknown GUID Name {E487EB08-6B26-4BE9-9DD3-993434D313FD}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: Unknown GUID Name {A33D2F7D-96BC-4337-B23B-A8B9FBC295E9}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 520

SUBTITLEINFO:
dwOffset: 520
IsoLang: eng
TrackName: 

pbFormat:
0000: 08 02 00 00 65 6e 67 00 00 00 00 00 00 00 00 00 ....eng.........
0010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0200: 00 00 00 00 00 00 00 00                         ........
```

Looks like it tries to load it but had absolutely no idea what it is

edit: styling correction

**Comment by bagusnl** [comment]
Update: looks like MPC-HC Internal Subtitle Rendered is also gets confused by this
It can load not-embedded vtt files but won't show any subtitle if the subtitle is embedded (which is technically the same thing)

MPC-HC 1.9.9.22
LAV 0.74.1.92-git

After some more digging I see that the problem has comes down  to FFmpeg issue from 5 years ago [here](https://trac.ffmpeg.org/ticket/5641) that has been dragged into [LAVFilters issue panel](https://github.com/Nevcairiel/LAVFilters/issues/80) and lastly [youtube-dl](https://github.com/ytdl-org/youtube-dl/issues/16338)

**Comment by ale5000-git** [comment]
This fork of LAVFilters support embedded WebVTT subtitles: https://github.com/clsid2/LAVFilters

**Comment by bagusnl** [comment]
> This fork of LAVFilters support embedded WebVTT subtitles: https://github.com/clsid2/LAVFilters

I see a commit regarding that around a day ago, so that's a good start. But, after a day experience of trying to build it, I don't seem to get it working. Something got so wrong with my system atm. Is there any pre-compiled release? Because I don't seem to find any
Thanks

**Comment by ale5000-git** [comment]
You can get it inside K-Lite Codec Pack.

With LAVFilters + internal subtitle render of MPC-HC you can see it working already but xy-VSFilter doesn't support them currently.

**Comment by bagusnl** [comment]
> You can get it inside here: https://files2.codecguide.com/beta/K-Lite_Codec_Pack_1609_Standard.exe
> 
> With LAVFilters + internal subtitle render of MPC-HC you can see it working already but xy-VSFilter doesn't support them currently.

Thank you!
It does finally show subtitles now, even though styled WebVTT subtitles just crapped out. But I think that one is a separate issue for the Internal Subtitle Renderer.
Pics:
![image](https://user-images.githubusercontent.com/28079733/111891176-69e47380-8a23-11eb-8493-304108ed4d10.png)

Edit: saw the new commits regarding the issue as clsid2 strips some unsupported styling format like shown in the image. I hope it will get better

**Comment by clsid2** [comment]
Yes, it should be fixed already.

**Comment by ale5000-git** [comment]
@bagusnl: Just for curiosity, what anime is the one in your screenshot?

**Comment by bagusnl** [comment]
> @bagusnl: Just for curiosity, what anime is the one in your screenshot?

@ale5000-git its [Natsuiro Matsuri's cover of Fansa](https://www.youtube.com/watch?v=xpUQ-5dSJTk) (from [Honeyworks//Mona Narumi](https://www.youtube.com/watch?v=lzyDD8bMDKs))

The WebVTT subtitle on the cover is pretty nice example for WebVTT styling where it has simple color set and top/bottom style for Romaji/English translation while not being over the top like [Nanawo Akari's Turing Love MV](https://www.youtube.com/watch?v=L-MVk5I6wjo) where it has blocks covering parts of video.

I attached both Matsuri's Fansa and Akari's Turing Love WebVTT below for reference

[Matsuri's Fansa WebVTT.txt](https://github.com/pinterf/xy-VSFilter/files/6176864/Matsuri.s.Fansa.WebVTT.txt)

[Akari's Turing Love WebVTT.txt](https://github.com/pinterf/xy-VSFilter/files/6176865/Akari.s.Turing.Love.WebVTT.txt)

**Comment by ale5000-git** [comment]
@bagusnl: K-Lite Codec Pack 16.1.0 include all fixes and now display them without noises.

**Comment by ale5000-git** [comment]
K-Lite Codec Pack 16.1.2 support also colors and some positions (not all).
