### ISSUE TITLE
Access violation on x64 build (potentially caused by `clip`)

### ISSUE THREAD

**Issue by shssoichiro** [pinterf/xy-VSFilter#2]
When running the x64 build of xy-vsfilter, I have been encountering frequent crashes of Avisynth-reliant applications due to access violations within VSFilter.dll, as exampled by the following Windows error log:

```
Faulting application name: x264.exe, version: 0.157.2940.0, time stamp: 0x5b6f3508
Faulting module name: VSFilter.dll, version: 3.1.0.800, time stamp: 0x5ace31a2
Exception code: 0xc0000005
Fault offset: 0x00000000000ce9aa
Faulting process id: 0x2188
Faulting application start time: 0x01d431e507194f11
Faulting application path: E:\Users\jholm\Documents\repos\x264\installed\bin\x264.exe
Faulting module path: C:\Program Files (x86)\AviSynth+\plugins64\VSFilter.dll
Report Id: cec3701e-bfe0-4d55-840c-039f3e479bb5
Faulting package full name: 
Faulting package-relative application ID: 
```

I suspect that usage of the ASS `clip` function in a certain way is causing this, as it seems to be present in all of the files which exhibit this crash, however not every script that includes `clip` is crashing. I have attached one of the scripts that does exhibit a crash: [[Coalgirls]_selector_infected_WIXOSS_01_(1920x1080_Blu-ray_FLAC)_[F6F99B9E].zip](https://github.com/pinterf/xy-VSFilter/files/2280735/Coalgirls._selector_infected_WIXOSS_01_.1920x1080_Blu-ray_FLAC._.F6F99B9E.zip)

Also of note is that every build I have tried of xy-vsfilter for x64 exhibits this issue, all the way back to https://github.com/Cyberbeing/xy-VSFilter/releases/tag/3.0.0.306. The vanilla x64 build of VSFilter 2.39 does not have this issue. I have not tested with a 32-bit build.

**Comment by pinterf** [comment]
I'm just running it quickly through a vdub session, but no crash for me. Or does it happen only with x264 encoding?Does it crash always at a specific location or it just simply happens at random places?
My script:
BlankClip(width=1920, height = 1080, color = $a10302, pixel_type = "YV12", length = 200000).Info()
TextSub("[Coalgirls]_selector_infected_WIXOSS_01_(1920x1080_Blu-ray_FLAC)_[F6F99B9E].ass",-1)

**Comment by shssoichiro** [comment]
Update: I have randomly encountered the crashes again, this time with about half of the scripts from Digimon Savers ([sample](https://github.com/pinterf/xy-VSFilter/files/2343508/RyRo._Digimon_Savers_-_03_.DVD_h264._.4AEC9B1B.zip)). And if I rerun the batch of failed encodes, half appear to be succeeding, but half appear to be crashing again, which means the crashes do seem to be random. These scripts do not contain `\clip` in them, so that appears to have been a red herring. The stack traces are still pointing back to xy-VSFilter.dll, however. The crashes are occurring approximately around the frame of the first subtitle, for the encodes where the crashes occur.

**Comment by pinterf** [comment]
(Running x264 encodings and avsmeter in the background, no crash so far.)
Thermal issues?

**Comment by pinterf** [comment]
Ok, could you please have a look at this test build?
http://www.mediafire.com/file/r97qbng6r3u9mai/xyVSFilterSubFilter-3.1.0.801.7z/file

**Comment by shssoichiro** [comment]
I ran through the set of episodes twice with the modified DLL and didn't encounter any crashes, which seems promising.

**Comment by shssoichiro** [comment]
Closing since it looks like this is fixed in the new release. Thanks!
