### ISSUE TITLE
Blank setting window

### ISSUE THREAD

**Issue by PhyX-Meow** [pinterf/xy-VSFilter#23]
I'm using madvr+lavfilter+xy-subfilter with potplayer, now my settings window of xy-subfilter look like this:

![image](https://user-images.githubusercontent.com/17513581/116048883-3e9b1700-a6a8-11eb-9768-e0171a1ec091.png)

Seems it's a font related issue. How can I make it display normally? Thanks for any advise.

LAV version: 0.75.0.2-git
xy-subfilter version: 14ef8ad30f3c75f961f30c0ff2085a7722078642
Windows version: 10.0.21364.1000 insider preview

**Comment by tkp206093** [comment]
I have same issue

**Comment by tkp206093** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/29872453/156893576-48629fbf-5803-4d75-8633-cbbfe561fa86.png">
off this option can fix this

**Comment by PhyX-Meow** [comment]
@tkp206093 Thanks！It works！
