### ISSUE TITLE
MaskSub crash if it used in script function

### ISSUE THREAD

**Issue by realfinder** [pinterf/xy-VSFilter#36]
hi, as the title said, here simple test case [test sample.zip](https://github.com/pinterf/xy-VSFilter/files/9997830/test.sample.zip)

**Comment by pinterf** [comment]
True statement. Reproduced. Will be investigated.

**Comment by pinterf** [comment]
Do you know accidentally why MaskSub is using an internal format MSP_RGBA (premultiplied alpha) instead of MSP_RGB32 (but only when using "RGB32" pixel_type (either ba having this as a default or given manually).
While TextSub filter is not working like that.
All is governed by setting an "RGBA" bool Avisynth variable, true-> MSP_RGBA, false -> MSP_RGB32?

**Comment by realfinder** [comment]
I have no idea, but I always wonder why it's flipped vertically, maybe @TheOneric know?

**Comment by pinterf** [comment]
RGB32 is stored upside down. But I'm gonna check is as well.

**Comment by pinterf** [comment]
As for flipping MaskSub, I found this:
https://forum.doom9.org/showthread.php?p=1819070&highlight=masksub#post1819070
and
https://forum.doom9.org/showthread.php?p=1957828&highlight=masksub#post1957828
It seems that FlipVertical is used in scripts. If I'd flip it back within the filter - as it would be logical - then existing scripts (do we have a lot ot them?) may become broken? 

EDIT: flipping occurs only at RGB32 (default) format. If pixel_type is different, it will show up normally. So I'd say, this present behaviour is not normal and must be fixed to be consistent across formats.

**Comment by pinterf** [comment]
This crash issue (exception) was reported here as well, in 2016.
https://forum.doom9.org/showthread.php?p=1788993#post1788993

**Comment by pinterf** [comment]
Pls. check pre-release v808

**Comment by realfinder** [comment]
tested with x64 and it work fine, thanks!
