### ISSUE TITLE
is textsub supposed to work with .sub files?

### ISSUE THREAD

**Issue by mbassiouny33** [pinterf/xy-VSFilter#41]
Hi

I noticed the documentation http://avisynth.nl/index.php/Xy-VSFilter  says:

> TextSub
> Adds subtitles from srt, **_sub_**, psb, smi, ssa, ass file formats.

But when I do  `textsub("myfile.sub")` it actually does not work.

But when I do  `VobSub("myfile.sub")` it works as expected.

Is the documentation on wiki wrong (@Reel-Deal a fix to the wiki entry might be needed ?) ? or is `textsub` supposed to be able to read vob subs as well?

Thanks

**Comment by clsid2** [comment]
There is also a text based format with extension .sub

**Comment by mbassiouny33** [comment]
Right! I totally forgot about that! My bad... Might be worth a small clarification in the wiki tho to avoid confusuon...

**Comment by Reel-Deal** [comment]
clsid2 is correct.  `Textsub` opens MicroDVD .sub files: https://en.wikipedia.org/wiki/MicroDVD and `VobSub` opens binary .sup files.
Maybe I should add the description from the [external filters page](http://avisynth.nl/index.php/External_filters#Subtitling): 

> Supported Subtitle Formats: VOBsub (.sub/.idx), SubStation Alpha/Advanced SubStation Alpha (.ssa/.ass), SubRip (.srt), MicroDVD (.sub), SAMI (.smi), PowerDivX (.psb), Universal Subtitle Format (.usf), Structured Subtitle Format (.ssf).

@mbassiouny33 - will do.
