### ISSUE TITLE
Supported for second sub

### ISSUE THREAD

**Issue by gsxgmpkt9020** [pinterf/xy-VSFilter#50]
Got to know it is not supported yet.

https://github.com/clsid2/mpc-hc/issues/2497#issuecomment-1984792477

DirectVobSub is too old and we need xy-VSFilter (pfmod)  to be compatiable with this in 2025

**Comment by clsid2** [comment]
You need to learn to read better.

xy-VSFilter is DirectVobSub.

XySubFilter is a different filter, and that will never be supported for second sub.

**Comment by gsxgmpkt9020** [comment]
The key is the way how player works. I remembered I used this with double subs in potplayer
